sonar.projectKey=AltaPay_plugin-shopware_6ff55bfb-f13e-4cba-a54c-9f0804511bbf
sonar.projectBaseDir=src
sonar.coverage.exclusions=**
sonar.cpd.exclusions=**
# Ignore Sonar rule: Property names should match ^[a-z][a-zA-Z0-9]*$
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S116
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.php